version: '3.8'

services:
  ssh-external-test:
    build:
      context: .
      dockerfile: Dockerfile.ssh-external-test
    container_name: ssh-external-test
    ports:
      - "2223:2222"
    volumes:
      - ./opk-providers-azure/providers:/etc/opk/providers:ro
      - ./opk-auth_id-azure/auth_id:/etc/opk/auth_id:ro
    networks:
      - external-test-net

networks:
  external-test-net:
    driver: bridge
